version: '3.8'

services:
  # TaskFlow Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://taskflow:taskflow@postgres:5432/taskflow
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-production-secret-change-this
    depends_on:
      - postgres
      - redis
    volumes:
      - app_data:/app/data
    restart: unless-stopped
    networks:
      - taskflow-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=taskflow
      - POSTGRES_USER=taskflow
      - POSTGRES_PASSWORD=taskflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - taskflow-network

  # Redis for Caching and Sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - taskflow-network
    command: redis-server --appendonly yes

  # Prisma Studio (Development)
  prisma-studio:
    image: node:18-alpine
    working_dir: /app
    command: npx prisma studio
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://taskflow:taskflow@postgres:5432/taskflow
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - taskflow-network
    profiles:
      - dev

volumes:
  postgres_data:
  redis_data:
  app_data:

networks:
  taskflow-network:
    driver: bridge