name: Bug Report
description: Create a report to help us improve
title: "[🐛 Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 😊
        
  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested this with the latest version
          required: true
        - label: I have read the documentation
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: A clear description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: A clear description of what actually happened
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Drag and drop images/videos here or paste URLs

  - type: dropdown
    id: environment-os
    attributes:
      label: Operating System
      description: What operating system are you running?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment-browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: input
    id: environment-node
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running?
      placeholder: e.g., 18.17.0
    validations:
      required: true

  - type: input
    id: environment-npm
    attributes:
      label: NPM Version
      description: What version of NPM are you using?
      placeholder: e.g., 9.6.7
    validations:
      required: true

  - type: textarea
    id: environment-additional
    attributes:
      label: Additional Environment Info
      description: Any other relevant environment information
      placeholder: |
        - Next.js version:
        - Database: SQLite/PostgreSQL
        - Deployment: Local/Vercel/Other

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please include any relevant error logs or console output
      placeholder: Paste error logs here
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any other information that might be helpful

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (cosmetic issue)
        - Medium (affects functionality)
        - High (breaks core features)
        - Critical (app unusable)
    validations:
      required: true