name: Feature Request
description: Suggest an idea for this project
title: "[✨ Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🎆
        
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: I have checked the documentation
          required: true
        - label: This is not a bug report (use bug report template instead)
          required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you'd like to see
      placeholder: One sentence describing the feature
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        **Is your feature request related to a problem?**
        A clear description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: A clear description of any alternative solutions or features you've considered

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - UI/UX Enhancement
        - New Component
        - API Enhancement
        - Performance Improvement
        - Developer Experience
        - Documentation
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would improve workflow)
        - High (significantly improves experience)
        - Critical (blocking current work)
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Describe how users would interact with this feature
      placeholder: |
        As a [user type],
        I want to [action],
        So that [benefit/goal]

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be implemented for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples
      placeholder: Drag and drop images here or paste URLs to examples from other applications

  - type: checkboxes
    id: implementation-considerations
    attributes:
      label: Implementation Considerations
      description: Check any that apply
      options:
        - label: This feature would require database changes
        - label: This feature would require new dependencies
        - label: This feature would affect existing APIs
        - label: This feature would require UI/UX design work
        - label: This feature would require documentation updates
        - label: This feature might affect performance
        - label: This feature might have security implications

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or screenshots about the feature request here
      placeholder: Any other information that would be helpful

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help with testing
        - label: I would be willing to help with documentation